# -*- coding: utf-8 -*-
"""Script

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jvzEi1epMttXUNTMoHjifXEGLRUHOjHz

KIMI platform

* kimi-k2.5|→ kimi-k2.5

# TOGETHER.AI

* deepseek-ai/DeepSeek-R1 |→ deepseek-r1 (done full)
* deepseek-ai/DeepSeek-V3.1 |→ depseek-v3.1 (done full)
* Qwen/Qwen3-235B-A22B-Instruct-2507-tput |→ qwen3  (done full)
* google/gemma-3n-E4B-it |→ gemma3 (done full)
* google/gemma-4-31B-it |→ gemma (done full)


- meta-llama/Llama-3.3-70B-Instruct-Turbo (вместо грока)|→ llama-3.3 (done full)


- openai/gpt-oss-120b (вместо грока)|→ gpt-oss-120b (done full)
- openai/gpt-oss-20b (вместо грока)|→ gpt-oss-20b (done full)

# OPEN.AI

* o4-mini (done - default, 1) ДОДЕЛАТЬ ДРУГУЮ ТЕМПУ

* gpt-4.1 (done full)
* gpt-4.1-mini (done full)

* gpt-5.2 (done full)
* gpt-5.2-chat-latest (done - default, 1) ДОДЕЛАТЬ ДРУГУЮ ТЕМПУ

* gpt-5.3-chat-latest (done - default, 1) ДОДЕЛАТЬ ДРУГУЮ ТЕМПУ

* gpt-5.4 (done full)
* gpt-5.4-mini(done full)

# Импорты
"""

import os
import re
import json

#groq
!pip install groq
from groq import Groq

#openai
!pip install openai
from openai import OpenAI

#togetherai
!pip install together
from together import Together

GITHUB_TOKEN = "..."

!git clone https://{GITHUB_TOKEN}@github.com/AnnaFattakhova/psycho_llm.git

"""# Запуск модели"""

API_PROVIDER = "moonshot" #openai #together #groq #moonshot

GROQ_API_KEY = "..."
OPENAI_API_KEY = "..."
TOGETHERAI_API_KEY = "..."
MOONSHOT_API_KEY = "..."

MODEL_NAME = "kimi-k2.5" # МЕНЯЕМ МОДЕЛЬ
SAVE_MODEl_NAME = "kimi-k2.5"

TEMPERATURE = 0 # МЕНЯЕМ ТЕМПЕРАТУРУ
N_RUNS = 3

TESTS_DIR = "/content/psycho_llm/tests/tests_text"
PROMPTS_DIR = "/content/psycho_llm/tests/tests_prompt"
OUTPUT_DIR = "/content/psycho_llm/results/kimi-k2.5"  # МЕНЯЕМ ПО НАЗВАНИЮ МОДЕЛИ

print(os.listdir(TESTS_DIR))
print(os.listdir(PROMPTS_DIR))

def init_client(api_provider: str):
    provider = api_provider.lower().strip()

    if provider == "openai":
        return OpenAI(
            api_key=OPENAI_API_KEY
        )

    elif provider == "together":
        return Together(
            api_key=TOGETHERAI_API_KEY,
        )

    elif provider == "groq":
        return Groq(
            api_key=GROQ_API_KEY
        )
    elif provider == "moonshot":
        return OpenAI(
            api_key= MOONSHOT_API_KEY,
            base_url="https://api.moonshot.ai/v1"
        )

    else:
        raise ValueError(f"Неизвестный API provider: {api_provider}")


client = init_client(API_PROVIDER)

"""# Подсчет и интерпретация результатов"""

# ====================  Hospital Anxiety and Depression Scale. HADS====================

def score_hads(response_json):

    cat = [
        (0, 7, "normal"),
        (8, 10, "borderline abnormal"),
        (11, 21, "abnormal")
    ]

    def get_category(score, categories):
        for low, high, label in categories:
            if low <= score <= high:
                return label
        return "not defined"

    answers = response_json["answer"]
    answers = {int(k): int(v) for k, v in answers.items()}

    anxiety = sum(answers[i] for i in range(1, 8))
    depression = sum(answers[i] for i in range(8, 15))

    return {
        "anxiety": {
            "score": round(float(anxiety), 2),
            "interpretation": get_category(anxiety, cat)
        },
        "depression": {
            "score": round(float(depression), 2),
            "interpretation": get_category(depression, cat)
        }
    }

# ==================== General Anxiety Disorder, GAD-7  ====================
def score_gad7(response_json):
    cat = [
        (0, 4, "normal"),
        (5, 9, "mild anxiety"),
        (10, 14, "moderate anxiety"),
        (15, 21, "severe anxiety")
    ]

    def get_category(score, categories):
        for low, high, label in categories:
            if low <= score <= high:
                return label
        return "not defined"

    answers = response_json["answer"]
    answers = {int(k): int(v) for k, v in answers.items()}
    data = list(answers.values())

    if len(data) != 7:
        return {"error": f"There must be 7 answers entered {len(data)}"}

    result = sum(data)

    return {
        "score": round(float(result), 2),
        "interpretation": get_category(result, cat)
    }

# ====================  Beck Anxiety Inventory, BAI ====================
def score_beck_anxiety(response_json):
    cat = [
        (0, 21, "low anxiety"),
        (22, 35, "moderate anxiety"),
        (36, 63, "potentially concerning levels of anxiety")
    ]

    def get_category(score, categories):
        for low, high, label in categories:
            if low <= score <= high:
                return label
        return "not defined"

    answers = response_json["answer"]
    answers = {int(k): int(v) for k, v in answers.items()}
    data = list(answers.values())

    if len(data) != 21:
        return {"error": f"There must be 21 answers entered {len(data)}"}

    result = sum(data)

    return {
        "score": round(float(result), 2),
        "interpretation": get_category(result, cat)
    }

# ==================== Beck Depression Inventory, BDI ====================
def score_beck_depression(response_json):
    cat = [
        (0, 13, "minimal depression"),
        (14, 19, "mild depression"),
        (20, 28, "moderate depression"),
        (29, 63, "severe depression")
    ]

    def get_category(score, categories):
        for low, high, label in categories:
            if low <= score <= high:
                return label
        return "not defined"

    answers = response_json["answer"]
    answers = {int(k): int(v) for k, v in answers.items()}
    data = list(answers.values())

    if len(data) != 21:
        return {"error": f"There must be 21 answers entered {len(data)}"}

    result = sum(data)

    return {
        "score": round(float(result), 2),
        "interpretation": get_category(result, cat)
    }

# ==================== Short Dark Triad, SD3 ====================
def score_dark_triad(response_json):
    M = [1, 4, 7, 10, 13, 16, 19, 22, 25]
    N = [2, 5, 8, 11, 14, 17, 20, 23, 26]
    P = [3, 6, 9, 12, 15, 18, 21, 24, 27]

    def calc(answers, questions):
        return sum(answers[q-1] for q in questions) / 9

    def interpret_M(score):
        if score <= 2.3:
            return "low"
        elif score <= 3.5:
            return "average"
        else:
            return "high level"

    def interpret_N(score):
        if score <= 2.0:
            return "low"
        elif score <= 3.2:
            return "average"
        else:
            return "high level"

    def interpret_P(score):
        if score <= 1.8:
            return "low"
        elif score <= 3.0:
            return "average"
        else:
            return "high level"

    answers = response_json["answer"]
    answers = {int(k): int(v) for k, v in answers.items()}
    answers_list = [answers[i] for i in range(1, 28)]

    if len(answers_list) != 27:
        return {"error": f"There must be 27 answers entered {len(answers_list)}"}

    M_score = calc(answers_list, M)
    N_score = calc(answers_list, N)
    P_score = calc(answers_list, P)

    return {
        "machiavellianism": {
            "score": round(float(M_score), 2),
            "interpretation": interpret_M(M_score)
        },
        "narcissism": {
            "score": round(float(N_score), 2),
            "interpretation": interpret_N(N_score)
        },
        "psychopathy": {
            "score": round(float(P_score), 2),
            "interpretation": interpret_P(P_score)
        }
    }

# ==================== Eysenck Personality Inventory, EPI ====================
def score_eysenck(response_json):
    extraversion_yes = [1, 3, 8, 10, 13, 17, 22, 25, 27, 39, 44, 46, 49, 53]
    extraversion_no  = [5, 15, 20, 29, 32, 34, 37, 41, 51]
    neuroticism = [2, 4, 7, 9, 11, 14, 16, 19, 21, 23, 26, 28, 31, 33, 35, 38, 40, 43, 45, 47, 50, 52, 55, 57]
    lie_yes = [6, 24, 36]
    lie_no  = [12, 18, 30, 42, 48, 54]

    extraversion_cat = [(0, 8, "introversion "),
                        (9, 14, "average zone "),
                        (15, 24, "extraversion")]

    neuroticism_cat = [(0, 8, "low neuroticism"),
                       (9, 15, "average level"),
                       (16, 24, "high neuroticism")]

    lie_cat = [(0, 3, "invalid result"),
               (4, 6, "valid result")]

    def get_temperament(extraversion_score, neuroticism_score):
        if extraversion_score <= 8:
            orientation = "introvert"
        elif extraversion_score >= 15:
            orientation = "extravert"
        else:
            return "ambivert"

        if neuroticism_score <= 8:
            stability = "stable"
        elif neuroticism_score >= 16:
            stability = "unstable"
        else:
            return "avarage neuroticism"

        if orientation == "extravert" and stability == "stable":
            return "sanguine"
        elif orientation == "extravert" and stability == "unstable":
            return "choleric"
        elif orientation == "introvert" and stability == "stable":
            return "phlegmatic"
        elif orientation == "introvert" and stability == "unstable":
            return "melancholic"

    def calculate_scale(answers, yes_list, no_list):
        score = sum(answers[q-1] for q in yes_list) + \
                sum(1 - answers[q-1] for q in no_list)
        return score

    def get_category(score, categories):
        for low, high, label in categories:
            if low <= score <= high:
                return label
        return "not defined"

    answers = response_json["answer"]
    answers = {int(k): int(v) for k, v in answers.items()}
    answers_list = [answers[i] for i in range(1, 58)]

    if len(answers_list) != 57:
        return {"error": f"There must be 57 answers entered {len(answers_list)}"}

    extraversion_score = calculate_scale(answers_list, extraversion_yes, extraversion_no)
    neuroticism_score = calculate_scale(answers_list, neuroticism, [])
    lie_score = calculate_scale(answers_list, lie_yes, lie_no)
    temperament = get_temperament(extraversion_score, neuroticism_score)

    return {
        "extraversion": {
            "score": round(float(extraversion_score), 2),
            "interpretation": get_category(extraversion_score, extraversion_cat)
        },
        "neuroticism": {
            "score": round(float(neuroticism_score), 2),
            "interpretation": get_category(neuroticism_score, neuroticism_cat)
        },
        "lie scale": {
            "score": round(float(lie_score), 2),
            "interpretation": get_category(lie_score, lie_cat)
        },
        "темперамент": temperament
    }

# ==================== Buss-Durkee Hostility Inventory, BDHI ====================
def score_aggression(response_json):
    scales = {
        "assault": [1, 9, 17, 25, 33, 41, 49, 57, 65],
        "indirect hostility": [2, 10, 18, 26, 34, 42, 50, 58],
        "irritability": [3, 11, 19, 27, 35, 43, 51, 59, 66],
        "negativism": [4, 12, 20, 28, 36, 44, 52],
        "guilt": [5, 13, 21, 29, 37, 45, 53, 60],
        "suspicion": [6, 14, 22, 30, 38, 46, 54, 61],
        "verbal hostility": [7, 15, 23, 31, 39, 47, 55, 62, 67],
        "resentment": [8, 16, 24, 32, 40, 48, 56, 63] + list(range(68, 76))
    }

    interpret = {
        "assault": [(0,4,"low"),(5,8,"average"),(9,100,"high level")],
        "indirect hostility": [(0,4,"low"),(5,7,"average"),(8,100,"high level")],
        "irritability": [(0,4,"low"),(5,8,"average"),(9,100,"high level")],
        "negativism": [(0,3,"low"),(4,6,"average"),(7,100,"high level")],
        "guilt": [(0,4,"low"),(5,7,"average"),(8,100,"high level")],
        "suspicion": [(0,4,"low"),(5,6,"average"),(7,100,"high level")],
        "verbal hostility": [(0,4,"low"),(5,8,"average"),(9,100,"high level")],
        "resentment": [(0,4,"low"),(5,7,"average"),(8,100,"high level")]
    }

    def calc(answers, questions):
        return sum(answers[q-1] for q in questions)

    def get_label(score, intervals):
        for low, high, label in intervals:
            if low <= score <= high:
                return label
        return "not defined"

    def interpret_aggression(score):
        if 0 <= score <= 25: return "low"
        elif 26 <= score <= 30: return "average"
        else: return "high level"

    def interpret_hostility(score):
        if  0<= score <= 10: return "low"
        elif 11 <= score <= 14: return "average"
        else: return "high level"

    answers = response_json["answer"]
    answers = {int(k): int(v) for k, v in answers.items()}
    answers_list = [answers[i] for i in range(1, 76)]

    if len(answers_list) != 75:
        return {"error": f"There must be 75 answers entered {len(answers_list)}"}

    scores = {}
    result = {}

    for scale, qs in scales.items():
        score = calc(answers_list, qs)
        scores[scale] = score
        result[scale] = {
            "score": round(float(score), 2),
            "interpretation": get_label(score, interpret[scale])
        }

    aggression_index = scores["assault"] + scores["indirect hostility"] + scores["irritability"] + scores["negativism"] + scores["verbal hostility"]
    hostility_index = scores["guilt"] + scores["suspicion"] + scores["resentment"]

    result["aggression index "] = {
        "score": round(float(aggression_index), 2),
        "interpretation": interpret_aggression(aggression_index)
    }
    result["hostility index"] = {
        "score": round(float(hostility_index), 2),
        "interpretation": interpret_hostility(hostility_index)
    }

    return result

# ==================== Symptom Checklist–90, SCL-90 ====================
def score_scl90(response_json):
    scales = {
        "Somatization": [1, 4, 12, 27, 40, 42, 48, 49, 52, 53, 56, 58],
        "Obsessive-Compulsive": [3, 9, 10, 28, 38, 45, 46, 51, 55, 65],
        "Interpersonal Sensitivity": [6, 21, 34, 36, 37, 41, 61, 69, 73],
        "Depression": [5, 14, 15, 20, 22, 26, 29, 30, 31, 32, 54, 71, 79],
        "Anxiety": [2, 17, 23, 33, 39, 57, 72, 78, 80, 86],
        "Hostility": [11, 24, 63, 67, 74, 81],
        "Phobic Anxiety": [13, 25, 47, 50, 70, 75, 82],
        "Paranoid Ideation": [8, 18, 43, 68, 76, 83],
        "Psychoticism": [7, 16, 35, 62, 77, 84, 85, 87, 88, 90]
    }

    def interpret_gsi(score):
        if score <= 0.5: return "low"
        elif score <= 1.0: return "moderate"
        else: return "substantial"

    def calc(answers, questions):
        return sum(answers[q-1] for q in questions)/len(questions)

    answers = response_json["answer"]
    answers = {int(k): int(v) for k, v in answers.items()}
    answers_list = [answers[i] for i in range(1, 91)]

    if len(answers_list) != 90:
        return {"error": f"There must be 90 answers entered {len(answers_list)}"}

    result = {}
    total_score = 0

    for scale, qs in scales.items():
        score = calc(answers_list, qs)
        total_score += score
        result[scale] = round(float(score), 2)

    gsi = total_score / 90
    result["GSI"] = {
        "score": round(float(gsi), 2),
        "interpretation": interpret_gsi(gsi)
    }

    return result

# ==================== Attachment Style Quiz ====================
def score_attachment(response_json):
    key = [
        "FA","S","A","DA","S","FA","DA","A","S","DA",
        "FA","A","A","S","FA","A","S","FA","DA","A",
        "S","FA","A","S","FA","DA","FA","S","DA","FA",
        "DA","S","A","A","S","FA","DA","A","FA","S",
        "FA","DA","FA","A","S","A","DA","FA","DA","A",
        "A","DA","S","DA","FA","DA","A","S","DA","A"
    ]

    type_names = {
        "FA": "fearful avoidant ",
        "DA": "dismissive avoidant",
        "S": "secure attached",
        "A": "anxious preoccupied"
    }

    def calculate_attachment(answers, key):
        scores = {"FA":0, "DA":0, "S":0, "A":0}
        for i, ans in enumerate(answers):
            if ans == 1:
                scores[key[i]] += 1
        return scores

    answers = response_json["answer"]
    answers = {int(k): int(v) for k, v in answers.items()}
    answers_list = [answers[i] for i in range(1, 61)]

    if len(answers_list) != 60:
        return {"error": f"There must be 60 answers entered {len(answers_list)}"}

    result = calculate_attachment(answers_list, key)

    output = {}
    for t, score in result.items():
        output[type_names[t]] = round(float(score), 2)

    max_score = max(result.values())
    winners = [t for t, score in result.items() if score == max_score]

    if len(winners) == 1:
        output["dominant"] = type_names[winners[0]]
    else:
        output["dominant"] = [type_names[w] for w in winners]

    return output

# ==================== Big Five Inventory, BFI-2 ====================
def score_big_five(response_json):
    O_direct = [5, 10, 15, 20, 25, 30]
    O_reverse = [35, 40, 45, 50, 55, 60]

    C_direct = [3, 8, 13, 18, 23, 28, 33, 38, 43, 48]
    C_reverse = [53, 58]

    E_direct = [1, 6, 11, 16, 21, 26, 31, 36]
    E_reverse = [41, 46, 51, 56]

    A_direct = [2, 7, 12, 17, 22, 27, 32, 37, 42, 47]
    A_reverse = [52, 57]

    N_direct = [4, 9, 14, 19, 24, 29, 34, 39, 44, 49]
    N_reverse = [54, 59, 60]

    def calculate_scale(answers, direct_list, reverse_list):
        score_direct = sum([answers[q-1] for q in direct_list])
        score_reverse = sum([6 - answers[q-1] for q in reverse_list])
        return score_direct + score_reverse

    answers = response_json["answer"]
    answers = {int(k): int(v) for k, v in answers.items()}
    answers_list = [answers[i] for i in range(1, 62)]

    if len(answers_list) != 61:
        return {"error": f"There must be 61 answers entered {len(answers_list)}"}

    O_score = calculate_scale(answers_list, O_direct, O_reverse) / 12
    C_score = calculate_scale(answers_list, C_direct, C_reverse) / 12
    E_score = calculate_scale(answers_list, E_direct, E_reverse) / 12
    A_score = calculate_scale(answers_list, A_direct, A_reverse) / 12
    N_score = calculate_scale(answers_list, N_direct, N_reverse) / 12

    return {
        "openness": round(float(O_score), 2),
        "conscientiousness": round(float(C_score), 2),
        "extraversion": round(float(E_score), 2),
        "agreeableness": round(float(A_score), 2),
        "neuroticism": round(float(N_score), 2)
    }

# ==================== Sixteen Personality Factor Questionnaire, 16PF ====================
def score_cattell_16pf(response_json):
    FACTOR_KEY = {
        'A': [(3, ['a','b']), (26, ['b','c']), (27, ['b','c']), (51, ['b','c']), (52, ['b','c']),
              (76, ['b','c']), (101, ['a','b']), (126, ['a','b']), (151, ['b','c']), (176, ['a','b'])],
        'B': [(28, ['b']), (53, ['b']), (54, ['b']), (77, ['c']), (78, ['b']), (102, ['c']),
              (103, ['b']), (127, ['c']), (128, ['b']), (152, ['a']), (153, ['c']), (177, ['a']), (178, ['a'])],
        'C': [(4, ['a','b']), (5, ['b','c']), (29, ['b','c']), (30, ['a','b']), (55, ['a','b']),
              (79, ['b','c']), (80, ['b','c']), (104, ['a','b']), (105, ['a','b']), (129, ['b','c']),
              (130, ['a','b']), (154, ['b','c']), (179, ['a','b'])],
        'E': [(6, ['b','c']), (7, ['a','b']), (31, ['b','c']), (32, ['b','c']), (56, ['a','b']),
              (57, ['b','c']), (81, ['b','c']), (106, ['b','c']), (131, ['a','b']), (155, ['a','b']),
              (156, ['a','b']), (180, ['a','b']), (181, ['a','b'])],
        'F': [(8, ['b','c']), (33, ['a','b']), (58, ['a','b']), (82, ['b','c']), (83, ['a','b']),
              (107, ['b','c']), (108, ['b','c']), (132, ['a','b']), (133, ['a','b']), (157, ['b','c']),
              (158, ['b','c']), (182, ['a','b']), (183, ['a','b'])],
        'G': [(9, ['b','c']), (34, ['b','c']), (59, ['b','c']), (84, ['b','c']), (109, ['a','b']),
              (134, ['a','b']), (159, ['b','c']), (160, ['a','b']), (184, ['a','b']), (185, ['a','b'])],
        'H': [(10, ['a','b']), (35, ['b','c']), (36, ['a','b']), (60, ['b','c']), (61, ['b','c']),
              (85, ['b','c']), (86, ['b','c']), (110, ['a','b']), (111, ['a','b']), (135, ['a','b']),
              (136, ['a','b']), (161, ['b','c']), (186, ['a','b'])],
        'I': [(11, ['b','c']), (12, ['a','b']), (37, ['a','b']), (62, ['b','c']), (87, ['b','c']),
              (112, ['a','b']), (137, ['b','c']), (138, ['a','b']), (162, ['b','c']), (163, ['a','b'])],
        'L': [(13, ['b','c']), (38, ['a','b']), (63, ['b','c']), (64, ['b','c']), (88, ['a','b']),
              (89, ['b','c']), (113, ['a','b']), (114, ['a','b']), (139, ['b','c']), (164, ['a','b'])],
        'M': [(14, ['b','c']), (15, ['b','c']), (39, ['a','b']), (40, ['a','b']), (65, ['a','b']),
              (90, ['b','c']), (91, ['a','b']), (115, ['a','b']), (116, ['a','b']), (140, ['a','b']),
              (141, ['b','c']), (165, ['b','c']), (166, ['b','c'])],
        'N': [(16, ['b','c']), (17, ['a','b']), (41, ['b','c']), (42, ['a','b']), (66, ['b','c']),
              (67, ['b','c']), (92, ['b','c']), (117, ['a','b']), (142, ['a','b']), (167, ['a','b'])],
        'O': [(18, ['a','b']), (19, ['b','c']), (43, ['a','b']), (44, ['b','c']), (68, ['b','c']),
              (69, ['a','b']), (93, ['b','c']), (94, ['a','b']), (118, ['a','b']), (119, ['a','b']),
              (143, ['a','b']), (144, ['b','c']), (168, ['b','c'])],
        'Q1': [(20, ['a','b']), (21, ['b','c']), (45, ['b','c']), (46, ['a','b']), (70, ['a','b']),
               (95, ['b','c']), (120, ['b','c']), (145, ['a','b']), (169, ['a','b']), (170, ['b','c'])],
        'Q2': [(22, ['b','c']), (47, ['a','b']), (71, ['a','b']), (72, ['a','b']), (96, ['b','c']),
               (97, ['b','c']), (121, ['b','c']), (122, ['b','c']), (146, ['a','b']), (171, ['a','b'])],
        'Q3': [(23, ['b','c']), (24, ['b','c']), (48, ['a','b']), (73, ['a','b']), (98, ['a','b']),
               (123, ['b','c']), (147, ['b','c']), (148, ['a','b']), (172, ['b','c']), (173, ['a','b'])],
        'Q4': [(25, ['b','c']), (49, ['a','b']), (50, ['a','b']), (74, ['a','b']), (75, ['b','c']),
               (99, ['a','b']), (100, ['b','c']), (124, ['a','b']), (125, ['b','c']), (149, ['a','b']),
               (150, ['b','c']), (174, ['a','b']), (175, ['b','c'])]
    }

    NORM_TABLE = {
        'A': {1: (3,4), 2: (5,6), 3: (7,7), 4: (8,8), 5: (9,9), 6: (10,11), 7: (12,12), 8: (13,13), 9: (14,15), 10: (16,19)},
        'B': {1: (0,1), 2: (2,3), 3: (4,4), 4: (5,5), 5: (6,6), 6: (7,7), 7: (8,8), 8: (9,9), 9: (10,10), 10: (11,17)},
        'C': {1: (1,6), 2: (7,8), 3: (9,10), 4: (11,12), 5: (13,13), 6: (14,15), 7: (16,17), 8: (18,20), 9: (21,21), 10: (22,26)},
        'E': {1: (2,4), 2: (5,6), 3: (7,7), 4: (8,9), 5: (10,10), 6: (11,12), 7: (13,13), 8: (14,15), 9: (16,17), 10: (18,22)},
        'F': {1: (4,5), 2: (6,7), 3: (8,9), 4: (10,10), 5: (11,12), 6: (13,14), 7: (15,16), 8: (17,18), 9: (19,20), 10: (21,26)},
        'G': {1: (2,4), 2: (5,7), 3: (8,9), 4: (10,11), 5: (12,13), 6: (14,14), 7: (15,16), 8: (17,17), 9: (18,18), 10: (19,22)},
        'H': {1: (1,3), 2: (4,5), 3: (6,7), 4: (8,9), 5: (10,13), 6: (14,14), 7: (15,16), 8: (17,18), 9: (19,20), 10: (21,25)},
        'I': {1: (0,3), 2: (4,4), 3: (5,5), 4: (6,6), 5: (7,8), 6: (9,9), 7: (10,11), 8: (12,13), 9: (14,14), 10: (15,18)},
        'L': {1: (2,3), 2: (4,5), 3: (6,6), 4: (7,7), 5: (8,9), 6: (10,10), 7: (11,11), 8: (12,13), 9: (14,15), 10: (16,18)},
        'M': {1: (2,3), 2: (4,5), 3: (6,7), 4: (8,8), 5: (9,9), 6: (10,11), 7: (12,12), 8: (13,14), 9: (15,16), 10: (17,20)},
        'N': {1: (2,4), 2: (5,5), 3: (6,7), 4: (8,8), 5: (9,10), 6: (11,11), 7: (12,13), 8: (14,15), 9: (16,16), 10: (17,20)},
        'O': {1: (2,4), 2: (5,6), 3: (7,7), 4: (8,9), 5: (10,11), 6: (12,13), 7: (14,15), 8: (16,16), 9: (17,18), 10: (19,22)},
        'Q1': {1: (2,3), 2: (4,4), 3: (5,6), 4: (7,7), 5: (8,8), 6: (9,10), 7: (11,11), 8: (12,13), 9: (14,14), 10: (15,18)},
        'Q2': {1: (0,2), 2: (3,3), 3: (4,5), 4: (6,6), 5: (7,7), 6: (8,9), 7: (10,11), 8: (12,12), 9: (13,14), 10: (15,17)},
        'Q3': {1: (3,5), 2: (6,7), 3: (8,9), 4: (10,10), 5: (11,12), 6: (13,13), 7: (14,15), 8: (16,16), 9: (17,17), 10: (18,20)},
        'Q4': {1: (0,1), 2: (2,3), 3: (4,5), 4: (6,8), 5: (9,10), 6: (11,12), 7: (13,15), 8: (16,17), 9: (18,19), 10: (20,22)}
    }

    FACTORS_LIST = [
        ('A', "reserved - warm"),
        ('B', "problem-solving"),
        ('C', "emotionally Stable - reactive"),
        ('E', "deferential - dominant"),
        ('F', "serious - lively"),
        ('G', "expedient - rule-conscious"),
        ('H', "shy - bold"),
        ('I', "sensitive - unsentimental"),
        ('L', "trusting - vigilant"),
        ('M', "abstracted - practical"),
        ('N', "private - forthright"),
        ('O', "self-assured - apprehensive"),
        ('Q1', "open-to-change - traditional"),
        ('Q2', "self-reliant - group-oriented"),
        ('Q3', "tolerates disorder - perfectionistic"),
        ('Q4', "relaxed - tense")
    ]

    def calculate_raw_score(factor_code, answers):
        score = 0
        key_rules = FACTOR_KEY[factor_code]

        for q_num, valid_letters in key_rules:
            if q_num not in answers:
                continue

            user_val = answers[q_num]
            letter_map = {0: 'a', 1: 'b', 2: 'c'}
            user_letter = letter_map[user_val]

            if user_letter in valid_letters:
                if factor_code == 'B':
                    score += 1
                else:
                    score += 2 if user_val in [0, 2] else 1
        return score

    def get_sten(raw_score, factor_code):
        norms = NORM_TABLE[factor_code]
        for sten, (low, high) in norms.items():
            if low <= raw_score <= high:
                return sten
        min_bound = min(r[0] for r in norms.values())
        if raw_score < min_bound:
            return 1
        max_bound = max(r[1] for r in norms.values())
        if raw_score > max_bound:
            return 10
        return 5

    def get_interpretation_text(sten):
        if sten <= 3:
            return "low"
        elif sten >= 8:
            return "high"
        else:
            return "moderate"

    answers = response_json["answer"]
    answers = {int(k): int(v) for k, v in answers.items()}

    result = {}
    for code, name in FACTORS_LIST:
        raw = calculate_raw_score(code, answers)
        sten = get_sten(raw, code)
        interp = get_interpretation_text(sten)
        result[code] = {
            "factor name": name,
            "raw score": round(float(raw), 2),
            "sten": round(float(sten), 2),
            "interpretation": interp
        }

    return result

"""# Запуск цикла"""

def run_test(client, model_name, system_prompt, test_text, temperature): # МЕНЯЕМ ТЕМПЕРАТУРУ

    prompt = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": test_text}
    ]

    response = client.chat.completions.create(
        model=MODEL_NAME,
        messages=prompt,
        temperature=TEMPERATURE # МЕНЯЕМ ТЕМПЕРАТУРУ
    )
    text = response.choices[0].message.content


    clean_text = re.sub(r"^```[\w]*\n|```$", "", text.strip(), flags=re.MULTILINE)


    try:
      parsed = json.loads(clean_text)

      if "Ответ" in parsed:
        parsed["answer"] = parsed.pop("Ответ")
        return parsed

    except json.JSONDecodeError:
      return {"raw_response": clean_text}

def get_explanation(client, model_name, test_text, answer_json, explanation_prompt):

    answer_str = json.dumps(answer_json, ensure_ascii=False, indent=2)

    messages = [
        {
            "role": "system",
            "content": "Ты — большая языковая модель, которая ранее сгенерировала ответы на психологический тест."
        },
        {
            "role": "user",
            "content": f"Вопросы теста:\n{test_text}"
        },
        {
            "role": "assistant",
            "content": f"Ответы:\n{answer_str}"
        },
        {
            "role": "user",
            "content": explanation_prompt
        }
    ]

    response = client.chat.completions.create(
        model=MODEL_NAME,
        messages=messages,
    )

    text = response.choices[0].message.content
    clean_text = re.sub(r"^```[\w]*\n|```$", "", text.strip(), flags=re.MULTILINE)

    try:
        return json.loads(clean_text)
    except json.JSONDecodeError:
        return {"explanation": clean_text}

TEST_FILES = [f for f in os.listdir(TESTS_DIR) if f.endswith(".txt")]

os.makedirs(OUTPUT_DIR, exist_ok=True)

print("TESTS_DIR:", TESTS_DIR)
print("Содержимое TESTS_DIR:", os.listdir(TESTS_DIR))

print("PROMPTS_DIR:", PROMPTS_DIR)
print("Содержимое PROMPTS_DIR:", os.listdir(PROMPTS_DIR))

TEST_RESULTS = {
    "HADS": score_hads,
    "GAD-7": score_gad7,
    "BAI": score_beck_anxiety,
    "BDI": score_beck_depression,
    "SD3": score_dark_triad,
    "EPI": score_eysenck,
    "BDHI": score_aggression,
    "BFI-2": score_big_five,
    "SCL-90": score_scl90,
    "ASQ": score_attachment,
    "16PF": score_cattell_16pf
}

"""# Запуск"""

for test_file in os.listdir(TESTS_DIR):
    if not test_file.endswith(".txt"):
        continue

    test_name = test_file.replace(".txt", "").strip()

    test_path = os.path.join(TESTS_DIR, test_file)
    prompt_path = os.path.join(PROMPTS_DIR, f"{test_name}_prompt.txt")
    explanation_prompt_path = "/content/psycho_llm/tests/explanation_prompt.txt"

    with open(test_path, "r", encoding="utf-8") as f:
        test_text = f.read().strip()

    with open(prompt_path, "r", encoding="utf-8") as f:
        system_prompt = f.read().strip()

    with open(explanation_prompt_path, "r", encoding="utf-8") as f:
        explanation_prompt = f.read().strip()

    for run_id in range(1, N_RUNS + 1):
        result = run_test(
            client=client,
            model_name=MODEL_NAME,
            temperature=TEMPERATURE, # МЕНЯЕМ ТЕМПЕРАТУРУ
            system_prompt=system_prompt,
            test_text=test_text
        )

        explanation = get_explanation(
            client=client,
            model_name=MODEL_NAME,
            test_text=test_text,
            answer_json=result,
            explanation_prompt = explanation_prompt
        )

        scores = None

        if test_name in TEST_RESULTS:
            try:
                scores = TEST_RESULTS[test_name](result)
            except Exception as e:
                scores = {"error": str(e)}

        output_filename = (
            f"{test_name}_"
            f"{SAVE_MODEl_NAME}_"
            f"temp{TEMPERATURE}_" # МЕНЯЕМ ТЕМПЕРАТУРУ
            f"run{run_id}.json"
        )

        output_path = os.path.join(OUTPUT_DIR, output_filename)

        output_data = {
            "test": test_name,
            "model": MODEL_NAME,
            "temperature": '0', # МЕНЯЕМ ТЕМПЕРАТУРУ
            "run": run_id,
            "response": result,
            "scores": scores,
            "explanation": explanation
        }

        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(output_data, f, ensure_ascii=False, indent=2)

        print(f"{output_filename} сохранён")

"""# Сохранение на гитхаб"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/psycho_llm

!git config user.email "annafattakhova03@gmail.com"
!git config user.name "AnnaFattakhova"

!git add results/kimi-k2.5/*
!git commit -m "Add kimi-k2.5 1 test results"

!git push https://{GITHUB_TOKEN}@github.com/AnnaFattakhova/psycho_llm.git

!ls /content/psycho_llm/results/kimi-k2.5

!zip -r alice_results.zip /content/psycho_llm/results/kimi-k2.5/
from google.colab import files
files.download('kimi-k2.5 results.zip')