# -*- coding: utf-8 -*-
"""Statistics hackaton

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E3r50nekZCRxWGLSVFrEIrxwPx0hqlfY
"""

import pandas as pd
import numpy as np
from scipy.stats import pearsonr
import matplotlib.pyplot as plt
import seaborn as sns

"""**r** — коэффициент корреляции(от -1 до +1; Если r = 0.88 → когда X растёт, Y почти всегда растёт тоже.)

| r       | Сила          |
| ------- | ------------- |
| 0.1–0.3 | слабая        |
| 0.3–0.7 | умеренная     |
| 0.7–1   | очень сильная |

**p** (случайность или нет) < 0.05 → значимо

**ci_low и ci_high** - то 95% доверительный интервал (в каком диапазоне находится "настоящая" корреляция): Мы на 95% уверены, что реальная корреляция лежит между ci_low и ci_high. Если интервал: не пересекает 0;  весь положительный → связь точно есть.



"""

df = pd.read_csv("/content/МАКСИМАЛЬНО ЧИСТЫЙ ХАКАТОН.csv")
print(df.head())

print(df.isna().sum())

df.info()

print(df.dtypes)

df = df.dropna()

"""# ***Корреляция для каждого человека отдельно***"""

results = []

for person in df["person_id"].unique():
    temp = df[df["person_id"] == person]

    if len(temp) >= 3:
        r, p = pearsonr(temp["human_score"], temp["model_score"])
        n = len(temp)

        # доверительный интервал через преобразование Фишера
        z = np.arctanh(r)
        se = 1 / np.sqrt(n - 3)
        z_crit = 1.96
        lo = z - z_crit * se
        hi = z + z_crit * se

        ci_low = np.tanh(lo)
        ci_high = np.tanh(hi)

        results.append([person, n, r, p, ci_low, ci_high])

results_df = pd.DataFrame(
    results,
    columns=["person_id", "n", "r", "p_value", "ci_low", "ci_high"]
)

def interpret_r(r):
    r = abs(r)
    if r < 0.3:
        return "weak"
    elif r < 0.7:
        return "moderate"
    elif r < 1:
        return "strong"

results_df["strength"] = results_df["r"].apply(interpret_r)

print(results_df)

"""# ***Корреляция по всей выборке***"""

# Общая корреляция
r, p = pearsonr(df["human_score"], df["model_score"])
n = len(df)

# Доверительный интервал через преобразование Фишера
z = np.arctanh(r)
se = 1 / np.sqrt(n - 3)
z_crit = 1.96
lo = z - z_crit * se
hi = z + z_crit * se

ci_low = np.tanh(lo)
ci_high = np.tanh(hi)

# Функция интерпретации
def interpret_r(r):
    r = abs(r)
    if r < 0.3:
        return "weak"
    elif r < 0.7:
        return "moderate"
    elif r < 1:
        return "strong"


overall_df = pd.DataFrame({
    "n": [n],
    "r": [r],
    "p_value": [p],
    "ci_low": [ci_low],
    "ci_high": [ci_high],
    "strength": [interpret_r(r)]
})

print(overall_df)

"""# ***Корреляция по тестам***

Мы берём один тест и смотрим насколько совпадают оценки модели и человека. насколько хорошо модель предсказывает именно этот тест?
"""

results = []

for test in df["test"].unique():

    temp = df[df["test"] == test]

    n = len(temp)

    # если слишком мало данных — пропускаем
    if n < 3:
        continue

    r, p = pearsonr(temp["human_score"], temp["model_score"])

    # доверительный интервал считаем только если r не идеальная
    if abs(r) < 0.999:

        z = np.arctanh(r)
        se = 1 / np.sqrt(n - 3)

        lo = z - 1.96 * se
        hi = z + 1.96 * se

        ci_low = np.tanh(lo)
        ci_high = np.tanh(hi)

    else:

        ci_low = np.nan
        ci_high = np.nan

    results.append([
        test,
        n,
        r,
        p,
        ci_low,
        ci_high
    ])

test_corr = pd.DataFrame(
    results,
    columns=[
        "test",
        "n",
        "r",
        "p_value",
        "ci_low",
        "ci_high"
    ]
)

test_corr = test_corr.sort_values("r", ascending=False)

pd.set_option("display.max_rows", None)

print(test_corr)

"""# ***Влияние тестов Leave-one-test-out***

какие тесты сильнее всего влияют на общую корреляцию между моделью и человеком.
"""

base_r, _ = pearsonr(df["human_score"], df["model_score"])

influence = []

for test in df["test"].unique():

    temp = df[df["test"] != test]   # убираем один тест

    r, _ = pearsonr(temp["human_score"], temp["model_score"])

    influence.append([
        test,
        r,
        base_r - r
    ])

influence_df = pd.DataFrame(
    influence,
    columns=["test", "r_without_test", "change_in_r"]
)

influence_df = influence_df.sort_values(
    "change_in_r",
    ascending=False
)

pd.set_option('display.max_rows', None)

print(influence_df)

base_r, _ = pearsonr(df["human_score"], df["model_score"])

influence = []

for test in df["test"].unique():

    temp = df[df["test"] != test]   # убираем один тест

    r, _ = pearsonr(temp["human_score"], temp["model_score"])

    influence.append([
        test,
        r,
        base_r - r
    ])

influence_df = pd.DataFrame(
    influence,
    columns=["test", "r_without_test", "change_in_r"]
)

influence_df = influence_df.sort_values(
    "change_in_r",
    ascending=False
)

pd.set_option('display.max_rows', None)

print(influence_df)

plt.figure(figsize=(12, 20))  # увеличиваем высоту

sns.barplot(
    x="change_in_r",
    y="test",
    data=influence_df,
    palette="coolwarm"
)

plt.axvline(0, color="k", linestyle="--")
plt.title("Влияние каждого теста на общую корреляцию")
plt.xlabel("Δr = r_base - r_without_test")
plt.ylabel("Test")

# Повернуть подписи, если они всё ещё налезают
plt.yticks(rotation=0, ha='right')

plt.tight_layout()
plt.show()

for test in df["test"].unique():
    temp = df[df["test"] == test]

    if len(temp) >= 3:
        plt.figure()
        sns.regplot(
            data=temp,
            x="human_score",
            y="model_score"
        )
        plt.title(f"{test}")
        plt.xlabel("Human score")
        plt.ylabel("Model score")
        plt.show()