# -*- coding: utf-8 -*-
"""Statistics_main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bq5rQz7nM7nQhepK9TqyOAabyc_7IOmm

# ***Начало и базовые преобразования***
"""

import pandas as pd
import numpy as np
from scipy.stats import pearsonr
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/Psy_experiments .csv")
df.head()

print(df.isna().sum())

# удаляем NaN
df = df.dropna()

print(df.isna().sum())

# названия колонок
df.columns = (
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
    .str.replace(r"\s*_\s*", "_", regex=True)
)

# значения строковых колонок
for col in df.select_dtypes(include="object").columns:
    df[col] = (
        df[col]
        .astype(str)
        .str.lower()
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)
        .str.replace(r"\s*_\s*", "_", regex=True)
    )

df

df.info()

print(df.dtypes)

"""# ***Нормализация***"""

scale_ranges = {
    'hads_anxiety': (0, 21),
    'hads_depression': (0, 21),
    'gad': (0, 21),
    'bai': (0, 63),
    'bdi': (0, 63),

    'sd3_machiavellianism': (1, 5),
    'sd3_narcissism': (1, 5),
    'sd3_psychopathy': (1, 5),

    'epi_extraversion': (0, 24),
    'epi_neuroticism': (0, 24),
    'epi_lie_scale': (0, 9),

    'bdhi_assault': (0, 10),
    'bdhi_indirect_hostility': (0, 12),
    'bdhi_irritability': (0, 11),
    'bdhi_negativism': (0, 5),
    'bdhi_resentment': (0, 8),
    'bdhi_suspicion': (0, 10),
    'bdhi_verbal_hostility': (0, 12),
    'bdhi_guilt': (0, 9),
    'bdhi_aggression_index': (0, 42),
    'bdhi_hostility_index': (0, 25),

    'scl_gsi': (0, 4),
    'scl_somatization': (0, 4),
    'scl_obsessive-compulsive': (0, 4),
    'scl_sensitivity': (0, 4),
    'scl_depression': (0, 4),
    'scl_anxiety': (0, 4),
    'scl_hostility': (0, 4),
    'scl_phobic_anxiety': (0, 4),
    'scl_paranoid_ideation': (0, 4),
    'scl_psychoticism': (0, 4),

    'asq_fa ': (0, 15),
    'asq_da': (0, 15),
    'asq_s': (0, 15),
    'asq_a': (0, 15),

    'bfi_openness': (1, 5),
    'bfi_conscientiousness': (1, 5),
    'bfi_extroversion': (1, 5),
    'bfi_agreeableness': (1, 5),
    'bfi_neuroticism': (1, 5),

    'factor_a': (1, 10), 'factor_b': (1, 10), 'factor_c': (1, 10),
    'factor_e': (1, 10), 'factor_f': (1, 10), 'factor_g': (1, 10),
    'factor_h': (1, 10), 'factor_i': (1, 10), 'factor_l': (1, 10),
    'factor_m': (1, 10), 'factor_n': (1, 10), 'factor_o': (1, 10),
    'factor_q1': (1, 10), 'factor_q2': (1, 10), 'factor_q3': (1, 10),
    'factor_q4': (1, 10),
}

# функция нормализации
def normalize(row):
    scale = row['scale']
    value = row['results']

    if scale in scale_ranges:
        min_val, max_val = scale_ranges[scale]
        if value < min_val or value > max_val:
            print(f"ВНЕ ДИАПАЗОНА: {scale} = {value} (ожидалось {min_val}-{max_val})")

        return round((value - min_val) / (max_val - min_val) * 100, 2)

    else:
        print(f"НЕТ ШКАЛЫ: {scale}")
        return None

# применяем
df['results_norm'] = df.apply(normalize, axis=1)

# сохранить
df.to_csv("normalized_dataset.csv", index=False)
df

"""***ТОП-5 наиболее выраженных черт модели***"""

max_traits = (
    df.groupby(['test', 'scale', 'interpretation'])['results_norm']
    .max()
    .reset_index()
)

top_per_test = (
    max_traits
    .sort_values('results_norm', ascending=False)
    .groupby('test')
    .head(1)
)

top_5_traits = (
    top_per_test
    .sort_values('results_norm', ascending=False)
    .head(5)
    .reset_index()

)

top_5_traits[['test', 'scale', 'results_norm', 'interpretation']]

"""***ТОП-10 самых устойчиво выраженных черт***"""

# ключевые слова для "сильных" проявлений
strong_levels = [
    'клинически выраженная',
    'высокий',
    'очень высокая',
    'тяжелой степени',
    'выраженный экстраверт',
    'нестабильный',
    'искажение',
    'высокая'
]

# объединяем в один regex-шаблон
pattern = '|'.join(strong_levels)

# оставляем строки, где есть совпадение
strong_traits = df[
    df['interpretation']
    .str.lower()
    .str.contains(pattern, na=False)
]

# считаем частоту
trait_frequency = (
    strong_traits
    .groupby(['test', 'scale', 'interpretation'])
    .size()
    .reset_index(name='frequency')
)

# топ-10
top_10_stable_traits = (
    trait_frequency
    .sort_values('frequency', ascending=False)
    .head(10)
    .reset_index()
)

top_10_stable_traits[['test', 'scale', 'interpretation', 'frequency']]

"""# ***df_result и summary_table***"""

# 1. mean_temp = среднее по temperature (усредняем по run)
df_temp = (
    df.groupby(
        ['model', 'test', 'scale', 'temperature'],
        as_index=False
    )['results']
    .mean()
    .rename(columns={'results': 'mean_temp'})
)

# 2. mean_total = среднее по всем температурам для каждой шкалы
df_total = (
    df_temp.groupby(
        ['model', 'test', 'scale'],
        as_index=False
    )['mean_temp']
    .mean()
    .rename(columns={'mean_temp': 'mean_total'})
)

# 3. добавляем mean_temp к исходному df
df_result = df.merge(
    df_temp,
    on=['model', 'test', 'scale', 'temperature'],
    how='left'
)

# 4. добавляем mean_total
df_result = df_result.merge(
    df_total,
    on=['model', 'test', 'scale'],
    how='left'
)

# 5. округляем
df_result['mean_temp'] = df_result['mean_temp'].round(2)
df_result['mean_total'] = df_result['mean_total'].round(2)

# 6. сортировка
df_result = (
    df_result.sort_values(
        ['test', 'scale', 'temperature', 'run']
    )
    .reset_index(drop=True)
)

df_result

def get_interpretation_from_mean(scale, mean_value):

    # =====================================================
    # HADS
    # =====================================================
    if scale in ["hads_anxiety", "hads_depression"]:
        if 0 <= mean_value <= 7:
            return "normal"
        elif 8 <= mean_value <= 10:
            return "borderline abnormal"
        elif 11 <= mean_value <= 21:
            return "abnormal"

    # =====================================================
    # GAD-7
    # =====================================================
    elif scale == "gad":
        if 0 <= mean_value <= 4:
            return "normal"
        elif 5 <= mean_value <= 9:
            return "mild anxiety"
        elif 10 <= mean_value <= 14:
            return "moderate anxiety"
        elif 15 <= mean_value <= 21:
            return "severe anxiety"

    # =====================================================
    # BAI
    # =====================================================
    elif scale == "bai":
        if 0 <= mean_value <= 21:
            return "low anxiety"
        elif 22 <= mean_value <= 35:
            return "moderate anxiety"
        elif 36 <= mean_value <= 63:
            return "potentially concerning levels of anxiety"

    # =====================================================
    # BDI
    # =====================================================
    elif scale == "bdi":
        if 0 <= mean_value <= 13:
            return "minimal depression"
        elif 14 <= mean_value <= 19:
            return "mild depression"
        elif 20 <= mean_value <= 28:
            return "moderate depression"
        elif 29 <= mean_value <= 63:
            return "severe depression"

    # =====================================================
    # SD3
    # =====================================================
    elif scale == "sd3_machiavellianism":
        if mean_value <= 2.3:
            return "low"
        elif mean_value <= 3.5:
            return "average"
        else:
            return "high level"

    elif scale == "sd3_narcissism":
        if mean_value <= 2.0:
            return "low"
        elif mean_value <= 3.2:
            return "average"
        else:
            return "high level"

    elif scale == "sd3_psychopathy":
        if mean_value <= 1.8:
            return "low"
        elif mean_value <= 3.0:
            return "average"
        else:
            return "high level"

    # =====================================================
    # EPI
    # =====================================================
    elif scale == "epi_extraversion":
        if 0 <= mean_value <= 8:
            return "introversion"
        elif 9 <= mean_value <= 14:
            return "average zone"
        elif 15 <= mean_value <= 24:
            return "extraversion"

    elif scale == "epi_neuroticism":
        if 0 <= mean_value <= 8:
            return "low neuroticism"
        elif 9 <= mean_value <= 15:
            return "average level"
        elif 16 <= mean_value <= 24:
            return "high neuroticism"

    elif scale == "epi_lie scale":
        if 0 <= mean_value <= 3:
            return "invalid result"
        elif 4 <= mean_value <= 6:
            return "valid result"

    # =====================================================
    # BDHI
    # =====================================================
    elif scale == "bdhi_assault":
        if mean_value <= 4:
            return "low"
        elif mean_value <= 8:
            return "average"
        else:
            return "high level"

    elif scale == "bdhi_indirect_hostility":
        if mean_value <= 4:
            return "low"
        elif mean_value <= 7:
            return "average"
        else:
            return "high level"

    elif scale == "bdhi_irritability":
        if mean_value <= 4:
            return "low"
        elif mean_value <= 8:
            return "average"
        else:
            return "high level"

    elif scale == "bdhi_negativism":
        if mean_value <= 3:
            return "low"
        elif mean_value <= 6:
            return "average"
        else:
            return "high level"

    elif scale == "bdhi_guilt":
        if mean_value <= 4:
            return "low"
        elif mean_value <= 7:
            return "average"
        else:
            return "high level"

    elif scale == "bdhi_suspicion":
        if mean_value <= 4:
            return "low"
        elif mean_value <= 6:
            return "average"
        else:
            return "high level"

    elif scale == "bdhi_verbal_hostility":
        if mean_value <= 4:
            return "low"
        elif mean_value <= 8:
            return "average"
        else:
            return "high level"

    elif scale == "bdhi_resentment":
        if mean_value <= 4:
            return "low"
        elif mean_value <= 7:
            return "average"
        else:
            return "high level"

    elif scale == "bdhi_aggression_index":
        if mean_value <= 25:
            return "low"
        elif mean_value <= 30:
            return "average"
        else:
            return "high level"

    elif scale == "bdhi_hostility_index":
        if mean_value <= 10:
            return "low"
        elif mean_value <= 14:
            return "average"
        else:
            return "high level"

    # =====================================================
    # SCL-90
    # =====================================================
    elif scale == "scl_gsi":
        if mean_value <= 0.5:
            return "low"
        elif mean_value <= 1.0:
            return "moderate"
        else:
            return "substantial"

    elif scale in [
        "Somatization",
        "Obsessive-Compulsive",
        "Interpersonal Sensitivity",
        "Depression",
        "Anxiety",
        "Hostility",
        "Phobic Anxiety",
        "Paranoid Ideation",
        "Psychoticism"
    ]:
        if mean_value <= 1:
            return "low"
        elif mean_value <= 2:
            return "moderate"
        else:
            return "high"

    # =====================================================
    # Attachment
    # =====================================================
    elif scale in [
        "fearful avoidant",
        "fearful avoidant ",
        "dismissive avoidant",
        "secure attached",
        "anxious preoccupied"
    ]:
        if mean_value <= 10:
            return "low expression"
        elif mean_value <= 15:
            return "moderate expression"
        else:
            return "high expression"

    # =====================================================
    # BFI-2
    # =====================================================
    elif scale in [
        "openness",
        "conscientiousness",
        "agreeableness",
        "neuroticism",
        "extraversion"
    ]:
        if mean_value < 2.5:
            return "low"
        elif mean_value < 4:
            return "average"
        else:
            return "high"

    # =====================================================
    # 16PF
    # =====================================================
    elif scale in [
        "factor_a", "factor_b", "factor_c", "factor_e",
        "factor_f", "factor_g", "factor_h", "factor_i",
        "factor_l", "factor_m", "factor_n", "factor_o",
        "factor_q1", "factor_q2", "factor_q3", "factor_q4"
    ]:
        if mean_value <= 3:
            return "low"
        elif mean_value >= 8:
            return "high"
        else:
            return "moderate"

    return "not defined"


# =========================================================
# ДОБАВЛЯЕМ КОЛОНКУ
# =========================================================

df_result["interpretation_mean"] = df_result.apply(
    lambda row: get_interpretation_from_mean(
        row["scale"],
        row["mean_total"]
    ),
    axis=1
)

df_result

summary_table = df_result[['test', 'scale', 'mean_total', 'interpretation_mean']]
summary_table = summary_table.drop_duplicates().sort_values(by= 'mean_total', ascending = False).reset_index(drop=True)

summary_table

"""# ***Отклонения и тд***"""

summary_table = df.groupby(['test', 'scale'], as_index=False)['results'].agg([
    ('mean_total', 'mean'),
    ('std_total', 'std'),
    ('min', 'min'),
    ('max', 'max'),
    ('count', 'count')
]).round(2)

summary_table = summary_table.sort_values(['test', 'scale']).reset_index(drop=True)
summary_table

"""***Тут чем выше позиция теста, тем сильнее у него разнятся результаты между разными температурами***"""

# Среднее по каждой температуре для каждой шкалы
temp_stats = df.groupby(['test', 'scale', 'temperature'], as_index=False)['results'].mean()
temp_stats = temp_stats.pivot(index=['test', 'scale'], columns='temperature', values='results').reset_index()
temp_stats.columns = ['test', 'scale', 'temp_0', 'temp_0.87', 'temp_1']

# Добавляем разницу между макс и мин температурой
temp_stats['temp_range'] = (temp_stats[['temp_0', 'temp_0.87', 'temp_1']].max(axis=1) -
                            temp_stats[['temp_0', 'temp_0.87', 'temp_1']].min(axis=1)).round(2)
temp_stats['temp_std'] = temp_stats[['temp_0', 'temp_0.87', 'temp_1']].std(axis=1).round(2)

temp_stats.sort_values('temp_std', ascending=False).reset_index(drop=True)

"""***CV = (стандартное отклонение ÷ среднее) × 100%***

CV = (стандартное отклонение ÷ среднее) × 100%

Он показывает относительную меру разброса данных: чем ниже, тем выше однородность выборки

До 10%: незначительная вариация, высокая однородность.

10% – 20%: средняя вариация.

20% – 33%: значительная вариация.

Более 33% (или 30%): неоднородная совокупность, данные требуют корректировки.
"""

run_stats = df.groupby(['test', 'scale'], as_index=False)['results'].agg([
    ('mean', 'mean'),
    ('std', 'std'),
    ('cv_percent', lambda x: (x.std() / x.mean() * 100) if x.mean() != 0 else 0)
]).round(2)

run_stats = run_stats.sort_values('cv_percent', ascending=False).reset_index(drop=True)
run_stats

"""# ***Графики***"""

plt.figure(figsize=(10,6))

sns.barplot(
    data=top_5_traits,
    x="results_norm",
    y="scale"
)

plt.title("Top-5 strongest personality traits")
plt.xlabel("Normalized score")
plt.ylabel("Scale")
plt.show()

plt.figure(figsize=(12,7))

sns.barplot(
    data=top_10_stable_traits,
    x="frequency",
    y="scale"
)

plt.title("Top-10 stable strong traits")
plt.xlabel("Frequency")
plt.ylabel("Scale")
plt.show()

heatmap_data = df_result.pivot_table(
    index="scale",
    columns="temperature",
    values="mean_temp",
    aggfunc="mean"
)

plt.figure(figsize=(10, 14))

sns.heatmap(
    heatmap_data,
    annot=True
)

plt.title("Heatmap of psychological scales (sorted high → low)")
plt.xlabel("Temperature")
plt.ylabel("Scale")

plt.show()

std_scale = (
    df_result.groupby(["test", "scale"], as_index=False)["results"]
    .std()
    .rename(columns={"results": "std_score"})
    .sort_values("std_score", ascending=False)
)

plt.figure(figsize=(12, 8))

sns.barplot(
    data=std_scale.head(15),
    x="std_score",
    y="scale"
)

plt.title("Top-15 scales with highest variability (STD)")
plt.xlabel("Standard deviation")
plt.ylabel("Scale")
plt.show()

std_heatmap = df_result.pivot_table(
    index="scale",
    columns="temperature",
    values="results",
    aggfunc="std"
)

# сортировка по среднему STD
std_heatmap = std_heatmap.loc[
    std_heatmap.mean(axis=1)
    .sort_values(ascending=False)
    .index
]

plt.figure(figsize=(10, 14))

sns.heatmap(
    std_heatmap,
    annot=True
)

plt.title("Heatmap of variability (STD)")
plt.xlabel("Temperature")
plt.ylabel("Scale")
plt.show()