# -*- coding: utf-8 -*-
"""Statistics hackaton_2_model-human

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U_CgthYEb2njwqa7dF4OOX1m_ZBtTQUR
"""

import pandas as pd
import numpy as np
from scipy.stats import pearsonr
import matplotlib.pyplot as plt
import seaborn as sns

merged_df = pd.read_csv("merged_df.csv")
print(merged_df.head())
print(merged_df.shape)

"""**r** — коэффициент корреляции(от -1 до +1; Если r = 0.88 → когда X растёт, Y почти всегда растёт тоже.)

| r       | Сила          |
| ------- | ------------- |
| 0.1–0.3 | слабая        |
| 0.3–0.7 | умеренная     |
| 0.7–1   | очень сильная |

**p** (случайность или нет) < 0.05 → значимо

**ci_low и ci_high** - то 95% доверительный интервал (в каком диапазоне находится "настоящая" корреляция): Мы на 95% уверены, что реальная корреляция лежит между ci_low и ci_high. Если интервал: не пересекает 0;  весь положительный → связь точно есть.



"""

df_total = pd.read_csv("/content/psycho_dataset - df_total.csv")
print(df_total.head())

df_сhakaton = pd.read_csv("/content/psycho_dataset - chakaton.csv")
print(df_сhakaton.head())
print(df_сhakaton.shape)

# удаляем ненужные столбцы
df_total = df_total.drop(columns=[
    "interpretation_mean",
    "mean_total_norm"
])

# объединяем таблицы
merged_df = df_сhakaton.merge(
    df_total,
    on=["model", "test", "scale"],
    how="left"
)

merged_df

#merged_df.to_csv('merged_df.csv')
df = merged_df

df["human_score"] = pd.to_numeric(df["human_score"], errors="coerce")
df["model_score"] = pd.to_numeric(df["model_score"], errors="coerce")
df["mean_total"] = pd.to_numeric(df["mean_total"], errors="coerce")

"""## ***Корреляция для каждого человека отдельно***"""

results = []

for person in df["person_id"].unique():
    temp = df[df["person_id"] == person]

    if len(temp) >= 3:
        r, p = pearsonr(temp["human_score"], temp["model_score"])
        n = len(temp)

        # доверительный интервал через преобразование Фишера
        z = np.arctanh(r)
        se = 1 / np.sqrt(n - 3)
        z_crit = 1.96
        lo = z - z_crit * se
        hi = z + z_crit * se

        ci_low = np.tanh(lo)
        ci_high = np.tanh(hi)

        results.append([person, n, r, p, ci_low, ci_high])

results_df = pd.DataFrame(
    results,
    columns=["person_id", "n", "r", "p_value", "ci_low", "ci_high"]
)

def interpret_r(r):
    r = abs(r)
    if r < 0.3:
        return "weak"
    elif r < 0.7:
        return "moderate"
    elif r < 1:
        return "strong"

results_df["strength"] = results_df["r"].apply(interpret_r)

print(results_df)

"""модели очень хорошо сохраняют структуру психологического профиля человека, то есть если человек тревожный, то и модель будет более тревожная

## ***Корреляция по всей выборке***
"""

# Общая корреляция
r, p = pearsonr(df["human_score"], df["model_score"])
n = len(df)

# Доверительный интервал через преобразование Фишера
z = np.arctanh(r)
se = 1 / np.sqrt(n - 3)
z_crit = 1.96
lo = z - z_crit * se
hi = z + z_crit * se

ci_low = np.tanh(lo)
ci_high = np.tanh(hi)

# Функция интерпретации
def interpret_r(r):
    r = abs(r)
    if r < 0.3:
        return "weak"
    elif r < 0.7:
        return "moderate"
    elif r < 1:
        return "strong"


overall_df = pd.DataFrame({
    "n": [n],
    "r": [r],
    "p_value": [p],
    "ci_low": [ci_low],
    "ci_high": [ci_high],
    "strength": [interpret_r(r)]
})

print(overall_df)

"""Для моделей"""

# Общая корреляция
r, p = pearsonr(df["mean_total"], df["model_score"])
n = len(df)

# Доверительный интервал через преобразование Фишера
z = np.arctanh(r)
se = 1 / np.sqrt(n - 3)
z_crit = 1.96
lo = z - z_crit * se
hi = z + z_crit * se

ci_low = np.tanh(lo)
ci_high = np.tanh(hi)

# Функция интерпретации
def interpret_r(r):
    r = abs(r)
    if r < 0.3:
        return "weak"
    elif r < 0.7:
        return "moderate"
    elif r < 1:
        return "strong"


overall_df = pd.DataFrame({
    "n": [n],
    "r": [r],
    "p_value": [p],
    "ci_low": [ci_low],
    "ci_high": [ci_high],
    "strength": [interpret_r(r)]
})

print(overall_df)

"""## ***Корреляция по тестам***

Мы берём один тест и смотрим насколько совпадают оценки модели и человека. насколько хорошо модель предсказывает именно этот тест?
"""

results = []

for test in df["test"].unique():

    temp = df[df["test"] == test]

    n = len(temp)

    # если слишком мало данных — пропускаем
    if n < 3:
        continue

    r, p = pearsonr(temp["human_score"], temp["model_score"])

    # доверительный интервал считаем только если r не идеальная
    if abs(r) < 0.999:

        z = np.arctanh(r)
        se = 1 / np.sqrt(n - 3)

        lo = z - 1.96 * se
        hi = z + 1.96 * se

        ci_low = np.tanh(lo)
        ci_high = np.tanh(hi)

    else:

        ci_low = np.nan
        ci_high = np.nan

    results.append([
        test,
        n,
        r,
        p,
        ci_low,
        ci_high
    ])

test_corr = pd.DataFrame(
    results,
    columns=[
        "test",
        "n",
        "r",
        "p_value",
        "ci_low",
        "ci_high"
    ]
)

test_corr = test_corr.sort_values("r", ascending=False)

pd.set_option("display.max_rows", None)

print(test_corr)

"""## ***Влияние тестов Leave-one-test-out***

какие тесты сильнее всего влияют на общую корреляцию между моделью и человеком.
"""

from scipy.stats import pearsonr
import pandas as pd

base_r, _ = pearsonr(df["human_score"], df["model_score"])

influence = []

for test in df["test"].unique():

    temp = df[df["test"] != test]

    r, _ = pearsonr(temp["human_score"], temp["model_score"])

    influence.append([
        test,
        round(r, 3),               # ← округление
        round(base_r - r, 3)       # ← округление
    ])

influence_df = pd.DataFrame(
    influence,
    columns=["test", "r_without_test", "change_in_r"]
)

influence_df = influence_df.sort_values(
    "change_in_r",
    ascending=False
)

pd.set_option('display.max_rows', None)

# если хочешь и base_r вывести красиво
print("Base r:", round(base_r, 3))

# сохранение
influence_df.to_csv(
    "r_score.csv",
    index=False
)

print(influence_df)

df["category"] = np.where(
    df["model_score"] > df["human_score"],
    "Overestimate",
    np.where(
        df["model_score"] < df["human_score"],
        "Underestimate",
        "Match"
    )
)


percentages = (
    df["category"]
    .value_counts(normalize=True) * 100
)

plt.figure(figsize=(7, 5))

sns.barplot(
    x=percentages.index,
    y=percentages.values
)

plt.ylabel("Процент")
plt.xlabel("")
plt.title("Совпадение")

for i, v in enumerate(percentages.values):
    plt.text(i, v + 1, f"{v:.1f}%", ha='center')

plt.show()

"""## Модель-человек"""

df["diff"] = df["model_score"] - df["human_score"]

pivot = df.pivot_table(
    values="diff",
    index="model",
    columns="scale",
    aggfunc="mean"
)

plt.figure(figsize=(20, 8))

cmap = sns.diverging_palette(
    240, 15,
    s=75,
    l=65,
    as_cmap=True
)

sns.heatmap(
    pivot,
    annot=True,
    cmap=cmap,
    center=0
)

#plt.title("Среднее расхождение между моделью и человеком")
plt.xlabel("Scale")
plt.ylabel("Model")

plt.tight_layout()

plt.savefig(
    "model_human_diff_heatmap.pdf",
    dpi=300,
    bbox_inches="tight",
    facecolor="white"
)

plt.show()

"""## Модель-модель"""

df["diff_model"] = df["model_score"] - df["mean_total"]

pivot = df.pivot_table(
    values="diff_model",
    index="model",
    columns="scale",
    aggfunc="mean"
)

plt.figure(figsize=(20, 8))

cmap = sns.diverging_palette(
    240, 15,
    s=75,
    l=65,
    as_cmap=True
)

sns.heatmap(
    pivot,
    annot=True,
    cmap=cmap,
    center=0
)

#plt.title("Среднее расхождение между моделью и человеком")
plt.xlabel("Scale")
plt.ylabel("Model")

plt.tight_layout()

plt.savefig(
    "model_model_diff_heatmap.pdf",
    dpi=300,
    bbox_inches="tight",
    facecolor="white"
)

plt.show()

"""Описать в тексте, без графика

Модель- человек
"""

df["category"] = np.where(
    df["model_score"] > df["human_score"],
    "Overestimate",
    np.where(
        df["model_score"] < df["human_score"],
        "Underestimate",
        "Match"
    )
)


percentages = (
    df["category"]
    .value_counts(normalize=True) * 100
)

plt.figure(figsize=(7, 5))

sns.barplot(
    x=percentages.index,
    y=percentages.values
)

plt.ylabel("Процент")
plt.xlabel("")
plt.title("Совпадение")

for i, v in enumerate(percentages.values):
    plt.text(i, v + 1, f"{v:.1f}%", ha='center')

plt.show()

"""Модель-модель

"""

df["category"] = np.where(
    df["model_score"] > df["mean_total"],
    "Overestimate",
    np.where(
        df["model_score"] < df["mean_total"],
        "Underestimate",
        "Match"
    )
)


percentages = (
    df["category"]
    .value_counts(normalize=True) * 100
)

plt.figure(figsize=(7, 5))

sns.barplot(
    x=percentages.index,
    y=percentages.values
)

plt.ylabel("Процент")
plt.xlabel("")
plt.title("Совпадение")

for i, v in enumerate(percentages.values):
    plt.text(i, v + 1, f"{v:.1f}%", ha='center')

plt.show()

"""Модель-человек"""

merged_df["abs_error_human"] = abs(
    merged_df["model_score"] - merged_df["human_score"]
)

mae = merged_df["abs_error_human"].mean()

print("MAE:", mae)

df.head()

"""**По моделям: по тестам или по шкалам??**
both
"""

import math

# ==========================================
# 1. DATA PREPARATION
# ==========================================
df_plot = df.copy()

# absolute deviations
df_plot["abs_error_human"] = (
    df_plot["model_score"] - df_plot["human_score"]
).abs()

df_plot["abs_error_model"] = (
    df_plot["model_score"] - df_plot["mean_total"]
).abs()

# ==========================================
# 2. AGGREGATION
# ==========================================
human_error = (
    df_plot
    .groupby(["model", "test"], as_index=False)
    ["abs_error_human"]
    .mean()
    .rename(columns={
        "abs_error_human": "error"
    })
)

human_error["comparison"] = "vs human_score"

mean_total_error = (
    df_plot
    .groupby(["model", "test"], as_index=False)
    ["abs_error_model"]
    .mean()
    .rename(columns={
        "abs_error_model": "error"
    })
)

mean_total_error["comparison"] = "vs mean_total"

plot_data = pd.concat([
    human_error,
    mean_total_error
])

# ==========================================
# 3. STYLE SETTINGS
# ==========================================
sns.set_style("whitegrid")

plt.rcParams.update({
    'font.weight': 'normal',
    'axes.labelweight': 'normal',
    'font.size': 12,
    'axes.titlesize': 14,
    'axes.labelsize': 12
})

# ==========================================
# 4. COLOR PALETTE
# ==========================================
cmap = sns.diverging_palette(
    240, 15,
    s=75,
    l=65,
    as_cmap=True
)

negative_color = cmap(0.15)
positive_color = cmap(0.85)

comparison_palette = {
    "vs human_score": negative_color,
    "vs mean_total": positive_color
}

# ==========================================
# 5. FACETGRID
# ==========================================
g = sns.FacetGrid(
    plot_data,
    col="model",
    col_wrap=2,     # ← 2 графика в строке
    sharex=True,
    sharey=False,
    height=8,
    aspect=2.2
)

# ==========================================
# 6. DRAW FUNCTION
# ==========================================
def draw_barplot(data, **kwargs):

    ax = plt.gca()

    # sorting
    order = (
        data.groupby("test")["error"]
        .mean()
        .sort_values()
        .index
    )

    data = data.copy()
    data["test"] = pd.Categorical(
        data["test"],
        categories=order,
        ordered=True
    )

    data = data.sort_values("test")

    sns.barplot(
        data=data,
        x="error",
        y="test",
        hue="comparison",
        palette=comparison_palette,
        orient="h",
        dodge=True,
        ax=ax,
        edgecolor='white',
        linewidth=1.3,
        alpha=0.92
    )

    # axes
    ax.set_xlabel(
        "MAE",
        fontsize=12,
        weight='normal',
        labelpad=12
    )

    ax.set_ylabel("")

    # ticks
    ax.tick_params(axis='y', pad=10)

    for label in ax.get_xticklabels():
        label.set_fontweight('normal')

    for label in ax.get_yticklabels():
        label.set_fontweight('normal')

    # grid
    ax.grid(
        axis='x',
        linestyle=':',
        alpha=0.4,
        linewidth=0.9,
        zorder=0
    )

    # spines
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_visible(False)

# ==========================================
# 7. DRAW
# ==========================================
g.map_dataframe(draw_barplot)

# ==========================================
# 8. TITLES
# ==========================================
g.set_titles(
    col_template="{col_name}",
    size=18,
    weight='normal',
    pad=25
)

# ==========================================
# 9. REMOVE DUPLICATE LEGENDS
# ==========================================
for ax in g.axes.flatten():

    legend = ax.get_legend()

    if legend is not None:
        legend.remove()

# ==========================================
# 10. GLOBAL LEGEND
# ==========================================
g.fig.legend(
    handles=[
        plt.Rectangle(
            (0, 0), 1, 1,
            color=negative_color
        ),
        plt.Rectangle(
            (0, 0), 1, 1,
            color=positive_color
        )
    ],
    labels=[
        "Model vs human",
        "Model vs model (interface)"
    ],
    loc='lower center',
    bbox_to_anchor=(0.5, 0.05),
    ncol=2,
    frameon=False,
    fontsize=14
)

# ==========================================
# 11. GRID SIZE
# ==========================================
n_models = len(plot_data["model"].unique())
n_cols = 2
n_rows = math.ceil(n_models / n_cols)

if n_models % n_cols == 1:

    axes = g.axes.flatten()

    last_ax = axes[n_models - 1]

    pos = last_ax.get_position()

    new_x0 = (1.0 - pos.width) / 2

    last_ax.set_position([
        new_x0,
        pos.y0,
        pos.width,
        pos.height
    ])

    for j in range(1, n_cols):

        idx = n_models - 1 + j

        if idx < len(axes):
            axes[idx].axis('off')

# ==========================================
# 12. SPACING
# ==========================================
g.fig.subplots_adjust(
    top=0.93,
    hspace=0.25,   # было 0.45
    wspace=0.25,   # было 0.45
    bottom=0.12    # чуть увеличим, чтобы легенда не наезжала
)

g.fig.set_size_inches(
    28,
    n_rows * 8.5
)

# ==========================================
# 13. SAVE
# ==========================================
plt.savefig(
    "model_vs_human_vs_mean_total_test.pdf",
    bbox_inches="tight",
    dpi=300,
    facecolor='white',
    pad_inches=0.4
)

plt.show()

import math
# ==========================================
# 1. DATA PREPARATION
# ==========================================
df_plot = df.copy()

df_plot["abs_error_human"] = (
    df_plot["model_score"] - df_plot["human_score"]
).abs()

df_plot["abs_error_model"] = (
    df_plot["model_score"] - df_plot["mean_total"]
).abs()

# ==========================================
# 2. AGGREGATION (BY SCALE)
# ==========================================
human_error = (
    df_plot
    .groupby(["model", "scale"], as_index=False)["abs_error_human"]
    .mean()
    .rename(columns={"abs_error_human": "error"})
)

human_error["comparison"] = "vs human_score"

mean_total_error = (
    df_plot
    .groupby(["model", "scale"], as_index=False)["abs_error_model"]
    .mean()
    .rename(columns={"abs_error_model": "error"})
)

mean_total_error["comparison"] = "vs mean_total"

plot_data = pd.concat([human_error, mean_total_error])

# ==========================================
# 3. STYLE (BIGGER TEXT)
# ==========================================
sns.set_style("whitegrid")

plt.rcParams.update({
    'font.weight': 'normal',
    'axes.labelweight': 'normal',
    'font.size': 14,
    'axes.titlesize': 18,
    'axes.labelsize': 14
})

# ==========================================
# 4. COLORS
# ==========================================
cmap = sns.diverging_palette(
    240, 15,
    s=75,
    l=65,
    as_cmap=True
)

negative_color = cmap(0.15)
positive_color = cmap(0.85)

comparison_palette = {
    "vs human_score": negative_color,
    "vs mean_total": positive_color
}

# ==========================================
# 5. FACETGRID (BIGGER PANELS)
# ==========================================
g = sns.FacetGrid(
    plot_data,
    col="model",
    col_wrap=2,
    sharex=True,
    sharey=False,
    height=10,     # увеличено
    aspect=3.2     # увеличено
)

# ==========================================
# 6. DRAW FUNCTION
# ==========================================
def draw_barplot(data, **kwargs):

    ax = plt.gca()

    order = (
        data.groupby("scale")["error"]
        .mean()
        .sort_values()
        .index
    )

    data = data.copy()
    data["scale"] = pd.Categorical(
        data["scale"],
        categories=order,
        ordered=True
    )

    data = data.sort_values("scale")

    sns.barplot(
        data=data,
        x="error",
        y="scale",
        hue="comparison",
        palette=comparison_palette,
        orient="h",
        dodge=True,
        ax=ax,
        edgecolor='white',
        linewidth=1.3,
        alpha=0.92
    )

    ax.set_xlabel(
        "MAE",
        fontsize=12,
        weight='normal',
        labelpad=12
    )

    ax.set_ylabel("")

    ax.tick_params(axis='y', pad=14)

    for label in ax.get_xticklabels():
        label.set_fontsize(13)
        label.set_fontweight('normal')

    for label in ax.get_yticklabels():
        label.set_fontsize(13)
        label.set_fontweight('normal')

    ax.grid(
        axis='x',
        linestyle=':',
        alpha=0.4,
        linewidth=0.9,
        zorder=0
    )

    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_visible(False)

# ==========================================
# 7. DRAW
# ==========================================
g.map_dataframe(draw_barplot)

# ==========================================
# 8. TITLES
# ==========================================
g.set_titles(
    col_template="{col_name}",
    size=20,
    weight='normal',
    pad=30
)

# ==========================================
# 9. REMOVE LEGENDS INSIDE PLOTS
# ==========================================
for ax in g.axes.flatten():
    leg = ax.get_legend()
    if leg is not None:
        leg.remove()

# ==========================================
# 10. GLOBAL LEGEND
# ==========================================
g.fig.legend(
    handles=[
        plt.Rectangle((0, 0), 1, 1, color=negative_color),
        plt.Rectangle((0, 0), 1, 1, color=positive_color)
    ],
    labels=[
        "Model vs human",
        "Model vs model (interface)"
    ],
    loc='lower center',
    bbox_to_anchor=(0.5, 0.07),
    ncol=2,
    frameon=False,
    fontsize=14
)

# ==========================================
# 11. GRID SIZE
# ==========================================
n_models = len(plot_data["model"].unique())
n_cols = 2
n_rows = math.ceil(n_models / n_cols)

if n_models % n_cols == 1:

    axes = g.axes.flatten()
    last_ax = axes[n_models - 1]

    pos = last_ax.get_position()
    new_x0 = (1.0 - pos.width) / 2

    last_ax.set_position([
        new_x0,
        pos.y0,
        pos.width,
        pos.height
    ])

    for j in range(1, n_cols):
        idx = n_models - 1 + j
        if idx < len(axes):
            axes[idx].axis('off')

# ==========================================
# 12. SPACING + SIZE
# ==========================================
g.fig.subplots_adjust(
    top=0.93,
    hspace=0.15,   # было 0.45
    wspace=0.15,   # было 0.45
    bottom=0.12    # чуть увеличим, чтобы легенда не наезжала
)
g.fig.set_size_inches(
    30,
    n_rows * 11
)

# ==========================================
# 13. SAVE
# ==========================================
plt.savefig(
    "model_vs_human_vs_mean_total_scale.pdf",
    bbox_inches="tight",
    dpi=300,
    facecolor='white',
    pad_inches=0.5
)

plt.show()

"""По тестам"""

# Используем LinearSegmentedColormap для плавного перехода
from matplotlib.colors import LinearSegmentedColormap
# ----------------------------
# DATA
# ----------------------------
test_error = (
    df.groupby("test")["abs_error_human"]
    .mean()
    .sort_values()
)

# ----------------------------
# CONTINUOUS COLOR GRADIENT
# ----------------------------
gradient_colors = ["#7BC67B", "#F2D16B", "#F4A259", "#E76F51"]

cmap = LinearSegmentedColormap.from_list(
    "error_gradient",
    gradient_colors,
    N=256
)

max_val = test_error.max()
min_val = test_error.min()

def get_gradient_color(val):
    norm_val = (
        (val - min_val) / (max_val - min_val)
        if max_val != min_val else 0
    )
    return cmap(norm_val)

# ----------------------------
# FIGURE
# ----------------------------
plt.figure(figsize=(12, 6))
ax = plt.gca()

# ----------------------------
# WHITE BACKGROUND
# ----------------------------
ax.set_facecolor("white")

# ----------------------------
# BARPLOT
# ----------------------------
ax = sns.barplot(
    x=test_error.values,
    y=test_error.index,
    color='#B0E0E6',
    zorder=3
)

# ----------------------------
# COLOR BARS WITH GRADIENT
# ----------------------------
for patch in ax.patches:
    val = patch.get_width()
    patch.set_facecolor(get_gradient_color(val))
    patch.set_alpha(0.85)
    patch.set_linewidth(1.0)

# ----------------------------
# AXES LABELS
# ----------------------------
plt.xlabel(
    "MAE",
    fontsize=11,
    fontweight='normal'
)

plt.ylabel(
    "Test",
    fontsize=11,
    fontweight='normal'
)

# ----------------------------
# TICKS
# ----------------------------
ax.tick_params(axis='both', labelsize=10)

for label in ax.get_xticklabels():
    label.set_fontweight('normal')

for label in ax.get_yticklabels():
    label.set_fontweight('normal')

# ----------------------------
# GRID
# ----------------------------
ax.grid(
    axis='x',
    alpha=0.15,
    linestyle=':',
    zorder=0
)

# ----------------------------
# LIMITS
# ----------------------------
ax.set_xlim(0, max_val * 1.08)

# ----------------------------
# SAVE
# ----------------------------
plt.tight_layout()

plt.savefig(
    'test_error_gradient_human.pdf',
    dpi=300,
    bbox_inches='tight',
    facecolor='white'
)

plt.show()

"""По шкалам"""

# ----------------------------
# DATA
# ----------------------------
test_error = (
    df.groupby("scale")["abs_error_human"]
    .mean()
    .sort_values()
)

# ----------------------------
# CONTINUOUS COLOR GRADIENT
# ----------------------------
gradient_colors = ["#7BC67B", "#F2D16B", "#F4A259", "#E76F51"]

cmap = LinearSegmentedColormap.from_list(
    "error_gradient",
    gradient_colors,
    N=256
)

max_val = test_error.max()
min_val = test_error.min()

def get_gradient_color(val):
    norm_val = (
        (val - min_val) / (max_val - min_val)
        if max_val != min_val else 0
    )
    return cmap(norm_val)

# ----------------------------
# FIGURE
# ----------------------------
plt.figure(figsize=(12, 6))
ax = plt.gca()

# ----------------------------
# WHITE BACKGROUND
# ----------------------------
ax.set_facecolor("white")

# ----------------------------
# BARPLOT
# ----------------------------
ax = sns.barplot(
    x=test_error.values,
    y=test_error.index,
    color='#B0E0E6',
    zorder=3
)

# ----------------------------
# COLOR BARS WITH GRADIENT
# ----------------------------
for patch in ax.patches:
    val = patch.get_width()
    patch.set_facecolor(get_gradient_color(val))
    patch.set_alpha(0.85)
    patch.set_linewidth(1.0)

# ----------------------------
# AXES LABELS
# ----------------------------
plt.xlabel(
    "MAE",
    fontsize=11,
    fontweight='normal'
)

plt.ylabel(
    "Scale",
    fontsize=11,
    fontweight='normal'
)

# ----------------------------
# TICKS
# ----------------------------
ax.tick_params(axis='both', labelsize=10)

for label in ax.get_xticklabels():
    label.set_fontweight('normal')

for label in ax.get_yticklabels():
    label.set_fontweight('normal')

# ----------------------------
# GRID
# ----------------------------
ax.grid(
    axis='x',
    alpha=0.15,
    linestyle=':',
    zorder=0
)

# ----------------------------
# LIMITS
# ----------------------------
ax.set_xlim(0, max_val * 1.08)

# ----------------------------
# SAVE
# ----------------------------
plt.tight_layout()

plt.savefig(
    'scale_error_gradient_human.pdf',
    dpi=300,
    bbox_inches='tight',
    facecolor='white'
)

plt.show()

"""Модель-модель"""

merged_df["abs_error_model"] = abs(
    merged_df["model_score"] - merged_df["mean_total"]
)

mae = merged_df["abs_error_model"].mean()

print("MAE:", mae)

"""По тестам"""

# ----------------------------
# DATA
# ----------------------------
test_error = (
    df.groupby("test")["abs_error_model"]
    .mean()
    .sort_values()
)

# ----------------------------
# CONTINUOUS COLOR GRADIENT
# ----------------------------
gradient_colors = ["#7BC67B", "#F2D16B", "#F4A259", "#E76F51"]

cmap = LinearSegmentedColormap.from_list(
    "error_gradient",
    gradient_colors,
    N=256
)

max_val = test_error.max()
min_val = test_error.min()

def get_gradient_color(val):
    norm_val = (
        (val - min_val) / (max_val - min_val)
        if max_val != min_val else 0
    )
    return cmap(norm_val)

# ----------------------------
# FIGURE
# ----------------------------
plt.figure(figsize=(12, 6))
ax = plt.gca()

# ----------------------------
# WHITE BACKGROUND
# ----------------------------
ax.set_facecolor("white")

# ----------------------------
# BARPLOT
# ----------------------------
ax = sns.barplot(
    x=test_error.values,
    y=test_error.index,
    color='#B0E0E6',
    zorder=3
)

# ----------------------------
# COLOR BARS WITH GRADIENT
# ----------------------------
for patch in ax.patches:
    val = patch.get_width()
    patch.set_facecolor(get_gradient_color(val))
    patch.set_alpha(0.85)
    patch.set_linewidth(1.0)

# ----------------------------
# AXES LABELS
# ----------------------------
plt.xlabel(
    "MAE",
    fontsize=11,
    fontweight='normal'
)

plt.ylabel(
    "Test",
    fontsize=11,
    fontweight='normal'
)

# ----------------------------
# TICKS
# ----------------------------
ax.tick_params(axis='both', labelsize=10)

for label in ax.get_xticklabels():
    label.set_fontweight('normal')

for label in ax.get_yticklabels():
    label.set_fontweight('normal')

# ----------------------------
# GRID
# ----------------------------
ax.grid(
    axis='x',
    alpha=0.15,
    linestyle=':',
    zorder=0
)

# ----------------------------
# LIMITS
# ----------------------------
ax.set_xlim(0, max_val * 1.08)

# ----------------------------
# SAVE
# ----------------------------
plt.tight_layout()

plt.savefig(
    'test_error_gradient_model.pdf',
    dpi=300,
    bbox_inches='tight',
    facecolor='white'
)

plt.show()

"""По шкалам"""

# ----------------------------
# DATA
# ----------------------------
test_error = (
    df.groupby("scale")["abs_error_model"]
    .mean()
    .sort_values()
)

# ----------------------------
# CONTINUOUS COLOR GRADIENT
# ----------------------------
gradient_colors = ["#7BC67B", "#F2D16B", "#F4A259", "#E76F51"]

cmap = LinearSegmentedColormap.from_list(
    "error_gradient",
    gradient_colors,
    N=256
)

max_val = test_error.max()
min_val = test_error.min()

def get_gradient_color(val):
    norm_val = (
        (val - min_val) / (max_val - min_val)
        if max_val != min_val else 0
    )
    return cmap(norm_val)

# ----------------------------
# FIGURE
# ----------------------------
plt.figure(figsize=(12, 6))
ax = plt.gca()

# ----------------------------
# WHITE BACKGROUND
# ----------------------------
ax.set_facecolor("white")

# ----------------------------
# BARPLOT
# ----------------------------
ax = sns.barplot(
    x=test_error.values,
    y=test_error.index,
    color='#B0E0E6',
    zorder=3
)

# ----------------------------
# COLOR BARS WITH GRADIENT
# ----------------------------
for patch in ax.patches:
    val = patch.get_width()
    patch.set_facecolor(get_gradient_color(val))
    patch.set_alpha(0.85)
    patch.set_linewidth(1.0)

# ----------------------------
# AXES LABELS
# ----------------------------
plt.xlabel(
    "MAE",
    fontsize=11,
    fontweight='normal'
)

plt.ylabel(
    "Scale",
    fontsize=11,
    fontweight='normal'
)

# ----------------------------
# TICKS
# ----------------------------
ax.tick_params(axis='both', labelsize=10)

for label in ax.get_xticklabels():
    label.set_fontweight('normal')

for label in ax.get_yticklabels():
    label.set_fontweight('normal')

# ----------------------------
# GRID
# ----------------------------
ax.grid(
    axis='x',
    alpha=0.15,
    linestyle=':',
    zorder=0
)

# ----------------------------
# LIMITS
# ----------------------------
ax.set_xlim(0, max_val * 1.08)

# ----------------------------
# SAVE
# ----------------------------
plt.tight_layout()

plt.savefig(
    'scale_error_gradient_model.pdf',
    dpi=300,
    bbox_inches='tight',
    facecolor='white'
)

plt.show()

"""Модель-человек"""

# "human_score" = mean_total

import matplotlib.pyplot as plt
import seaborn as sns

# ----------------------------
# DATA
# ----------------------------
scale_diff = (
    df.groupby("scale")["diff"]
    .mean()
    .sort_values()
)

# ----------------------------
# DIVERGING PALETTE
# ----------------------------
cmap = sns.diverging_palette(
    240, 15,
    s=75,
    l=65,
    as_cmap=True
)

# берем два цвета из палитры:
negative_color = cmap(0.15)   # синий
positive_color = cmap(0.85)   # розовый

colors = [
    positive_color if x > 0 else negative_color
    for x in scale_diff.values
]

# ----------------------------
# FIGURE
# ----------------------------
plt.figure(figsize=(12, 10))
ax = plt.gca()

ax.set_facecolor("white")

# ----------------------------
# BARPLOT
# ----------------------------
plt.barh(
    scale_diff.index,
    scale_diff.values,
    color=colors,
    alpha=0.9
)

# ----------------------------
# ZERO LINE
# ----------------------------
plt.axvline(
    0,
    color="black",
    linestyle="--",
    linewidth=0.8,
    alpha=0.5
)

# ----------------------------
# LABELS
# ----------------------------
plt.xlabel(
    "Systematic bias",
    fontsize=11,
    fontweight='normal'
)

plt.ylabel(
    "Scale",
    fontsize=11,
    fontweight='normal'
)

# ----------------------------
# TICKS
# ----------------------------
ax.tick_params(axis='both', labelsize=10)

for label in ax.get_xticklabels():
    label.set_fontweight('normal')

for label in ax.get_yticklabels():
    label.set_fontweight('normal')

# ----------------------------
# GRID
# ----------------------------
ax.grid(
    axis='x',
    alpha=0.35,
    linestyle=':',
    linewidth=1.2
)

ax.grid(axis='y', visible=False)
# ----------------------------
# SAVE
# ----------------------------
plt.tight_layout()

plt.savefig(
    "scale_diff_bias_human.pdf",
    dpi=300,
    bbox_inches="tight",
    facecolor="white",
    pad_inches=0.3
)


plt.show()

"""Модель-модель"""

# ----------------------------
# DATA
# ----------------------------
scale_diff = (
    df.groupby("scale")["diff_model"]
    .mean()
    .sort_values()
)

# ----------------------------
# DIVERGING PALETTE
# ----------------------------
cmap = sns.diverging_palette(
    240, 15,
    s=75,
    l=65,
    as_cmap=True
)

# берем два цвета из палитры:
negative_color = cmap(0.15)   # синий
positive_color = cmap(0.85)   # розовый

colors = [
    positive_color if x > 0 else negative_color
    for x in scale_diff.values
]

# ----------------------------
# FIGURE
# ----------------------------
plt.figure(figsize=(12, 10))
ax = plt.gca()

ax.set_facecolor("white")

# ----------------------------
# BARPLOT
# ----------------------------
plt.barh(
    scale_diff.index,
    scale_diff.values,
    color=colors,
    alpha=0.9
)

# ----------------------------
# ZERO LINE
# ----------------------------
plt.axvline(
    0,
    color="black",
    linestyle="--",
    linewidth=0.8,
    alpha=0.5
)

# ----------------------------
# LABELS
# ----------------------------
plt.xlabel(
    "Systematic bias",
    fontsize=11,
    fontweight='normal'
)

plt.ylabel(
    "Scale",
    fontsize=11,
    fontweight='normal'
)

# ----------------------------
# TICKS
# ----------------------------
ax.tick_params(axis='both', labelsize=10)

for label in ax.get_xticklabels():
    label.set_fontweight('normal')

for label in ax.get_yticklabels():
    label.set_fontweight('normal')

# ----------------------------
# GRID
# ----------------------------
ax.grid(
    axis='x',
    alpha=0.35,
    linestyle=':',
    linewidth=1.2
)

ax.grid(axis='y', visible=False)
# ----------------------------
# SAVE
# ----------------------------
plt.tight_layout()

plt.savefig(
    "scale_diff_bias_model.pdf",
    dpi=300,
    bbox_inches="tight",
    facecolor="white",
    pad_inches=0.3
)

plt.show()

"""SYSTEMATIC BIAS

То есть: модель в среднем завышает или занижает оценки?
bias > 0
модель завышает показатели.

bias < 0
модель занижает.

bias ≈ 0
систематического смещения нет.
"""

df["diff"] = df["model_score"] - df["human_score"]

overall_bias = df["diff"].mean()

print("Overall bias:", overall_bias)

df["diff"] = df["model_score"] - df["mean_total"]

overall_bias = df["diff_model"].mean()

print("Overall bias:", overall_bias)

scale_bias = (
    df.groupby("scale")["diff"]
    .mean()
    .sort_values(ascending=False)
)

print(scale_bias)

"""Насколько модели ошибаются В СРЕДНЕМ."""

df["abs_error"] = abs(
    df["model_score"] - df["human_score"]
)

mae = df["abs_error"].mean()

print("MAE:", mae)

mae_by_scale = (
    df.groupby("scale")["abs_error"]
    .mean()
    .sort_values(ascending=False)
)

print(mae_by_scale)

"""График—сравнение трех"""

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# ==========================================
# 1. DATA PREPARATION
# ==========================================
target_scales = ['epi_extraversion', 'epi_neuroticism']

df_traits = df[
    df['scale'].isin(target_scales)
].copy()

# ==========================================
# 2. AGGREGATION
# ==========================================
df_agg = (
    df_traits
    .groupby(['model', 'scale'], as_index=False)
    .agg({
        'mean_total': 'mean',
        'human_score': 'mean',
        'model_score': 'mean'
    })
)

# ==========================================
# 3. WIDE TABLES
# ==========================================
mean_total_wide = (
    df_agg
    .pivot(index='model', columns='scale', values='mean_total')
    .reset_index()
)

mean_total_wide['source'] = 'mean_total'

human_wide = (
    df_agg
    .pivot(index='model', columns='scale', values='human_score')
    .reset_index()
)

human_wide['source'] = 'human_score'

model_wide = (
    df_agg
    .pivot(index='model', columns='scale', values='model_score')
    .reset_index()
)

model_wide['source'] = 'model_score'

# ==========================================
# 4. COMBINE
# ==========================================
plot_df = pd.concat([
    mean_total_wide,
    human_wide,
    model_wide
])

plot_df = plot_df.dropna(
    subset=['epi_extraversion', 'epi_neuroticism']
)

# ==========================================
# 5. TEMPERAMENT CLASSIFICATION
# ==========================================
MIDPOINT = 12

def assign_temperament(row):

    ext = row['epi_extraversion']
    neuro = row['epi_neuroticism']

    # stable + extravert
    if ext >= MIDPOINT and neuro < MIDPOINT:
        return 'Sanguine'

    # stable + introvert
    elif ext < MIDPOINT and neuro < MIDPOINT:
        return 'Phlegmatic'

    # unstable + introvert
    elif ext < MIDPOINT and neuro >= MIDPOINT:
        return 'Melancholic'

    # unstable + extravert
    else:
        return 'Choleric'

plot_df['temperament'] = plot_df.apply(
    assign_temperament,
    axis=1
)

# ==========================================
# 6. STYLE
# ==========================================
sns.set_theme(style="white")

plt.rcParams.update({
    'font.family': 'sans-serif',
    'font.weight': 'normal',
    'axes.labelweight': 'normal',
    'font.size': 10
})

fig, ax = plt.subplots(figsize=(10, 10))

# ==========================================
# 7. BACKGROUND ZONES
# ==========================================

# bottom-left
ax.axvspan(
    0, MIDPOINT,
    0, 0.5,
    facecolor='#cce5ff',
    alpha=0.35,
    zorder=0
)

# bottom-right
ax.axvspan(
    MIDPOINT, 24,
    0, 0.5,
    facecolor='#7BC67B',
    alpha=0.35,
    zorder=0
)

# top-left
ax.axvspan(
    0, MIDPOINT,
    0.5, 1.0,
    facecolor='#F2D16B',
    alpha=0.35,
    zorder=0
)

# top-right
ax.axvspan(
    MIDPOINT, 24,
    0.5, 1.0,
    facecolor='#E76F51',
    alpha=0.35,
    zorder=0
)

# ==========================================
# 8. QUADRANT LABELS
# ==========================================
ax.text(
    6,
    1.0,
    'Phlegmatic',
    ha='center',
    va='bottom',
    fontsize=11,
    style='italic',
    color='#555555',
    alpha=0.7
)

ax.text(
    18,
    1.0,
    'Sanguine',
    ha='center',
    va='bottom',
    fontsize=11,
    style='italic',
    color='#555555',
    alpha=0.7
)

ax.text(
    6,
    13.0,
    'Melancholic',
    ha='center',
    va='bottom',
    fontsize=11,
    style='italic',
    color='#555555',
    alpha=0.7
)

ax.text(
    18,
    13.0,
    'Choleric',
    ha='center',
    va='bottom',
    fontsize=11,
    style='italic',
    color='#555555',
    alpha=0.7
)

# ==========================================
# 9. COLORS
# ==========================================
source_palette = {
    'human_score': '#dd8452',
    'model_score': '#55a868',
    'mean_total': '#4c72b0'
}

# ==========================================
# 10. SCATTERPLOT
# ==========================================
sns.scatterplot(
    data=plot_df,
    x='epi_extraversion',
    y='epi_neuroticism',
    hue='source',
    palette=source_palette,
    s=160,
    edgecolor='black',
    linewidth=0.7,
    alpha=0.9,
    ax=ax,
    zorder=3
)

# ==========================================
# 11. AXES
# ==========================================
ax.set_xlim(0, 24)
ax.set_ylim(0, 24)

ax.set_xlabel(
    'Extraversion',
    fontsize=12,
    fontweight='normal'
)

ax.set_ylabel(
    'Neuroticism',
    fontsize=12,
    fontweight='normal'
)

# midpoint threshold lines
ax.axhline(
    MIDPOINT,
    color='gray',
    linestyle='--',
    linewidth=0.8,
    alpha=0.5,
    zorder=1
)

ax.axvline(
    MIDPOINT,
    color='gray',
    linestyle='--',
    linewidth=0.8,
    alpha=0.5,
    zorder=1
)

# ticks
ax.tick_params(
    axis='both',
    labelsize=10
)

for label in ax.get_xticklabels():
    label.set_fontweight('normal')

for label in ax.get_yticklabels():
    label.set_fontweight('normal')

# grid
ax.grid(
    True,
    linestyle=':',
    alpha=0.3,
    zorder=0
)

ax.spines[['top', 'right']].set_visible(False)

# ==========================================
# 12. LEGEND
# ==========================================
handles, labels = ax.get_legend_handles_labels()

label_map = {
    'human_score': 'human_score',
    'model_score': 'model_score',
    'mean_total': 'model_interface_score'
}

new_labels = [
    label_map.get(l, l)
    for l in labels
]

legend = ax.legend(
    handles,
    new_labels,
    title='Score type',
    title_fontsize=11,
    fontsize=10,
    frameon=True,
    edgecolor='#cccccc',
    facecolor='white'
)

legend.get_title().set_fontweight('normal')

for t in legend.get_texts():
    t.set_fontweight('normal')

# ==========================================
# 13. SAVE
# ==========================================
plt.tight_layout()

plt.savefig(
    'temperament_comparison_equal_quadrants.pdf',
    dpi=300,
    bbox_inches='tight',
    facecolor='white'
)

plt.show()
